using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class SecretDropdown : MonoBehaviour
{
    public enum SecretPlanet
    {
        Сонце, Меркурій, Венера, Місяць, Марс, Юпітер, Сатурн, Уран, Нептун, Земля
    }

    [SerializeField] private TMP_Dropdown _dropdown;
    [SerializeField] private SecretPlanet _planet;
    [SerializeField] private TextMeshProUGUI _planetNameText;

    public TMP_Dropdown Dropdown => _dropdown;
    public int PlanetIndex => (int)_planet;

    void Start()
    {
        if (_planetNameText != null)
            _planetNameText.text = _planet.ToString();
        _dropdown.onValueChanged.AddListener(OnValueChanged);
    }

    void OnValueChanged(int index)
    {
        if (_planetNameText != null)
            _planetNameText.text = _planet.ToString();
    }
}
